modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "respawnobelisks"
version = "${version}"
displayName = "Respawn Obelisks"
authors = "RedPxnda"
description = '''
A simple mod about overhauling the respawning system.
'''
#logoFile = ""

[[dependencies.respawnobelisks]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.respawnobelisks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.respawnobelisks]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"