modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/RedPxnda/RespawnObelisks/issues"
license = "MIT"

[[mods]]
modId = "respawnobelisks"
version = "${version}"
displayName = "Respawn Obelisks"
authors = "RedPxnda"
description = '''
A simple mod about overhauling the respawning system.
'''
#logoFile = ""

[[dependencies.respawnobelisks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.respawnobelisks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.respawnobelisks]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"