name: Build and Release Project
on: [ workflow_dispatch ]
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Publish Pre Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          build/libs/*-all.jar
    - name: "Upload to CurseForge"
      uses: itsmeow/curseforge-upload@v3
      with:
        file_path: "build/libs/respawnobelisks-${{ steps.build.outputs.version }}-all.jar"
        changelog: "https://github.com/RedPxnda/RespawnObelisks/wiki/Changelog"
        game_endpoint: "minecraft"
        game_versions: "Minecraft 1.19:1.19.2,Java 17,Forge"
        project_id: "824852"
        token: "${{ secrets.CF_API_TOKEN }}"
