name: Build and Release Project
on: [ workflow_dispatch ]
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Publish Pre Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Full Release Build"
        files: |
          build/libs/*-all.jar
#     - name: "Upload to CurseForge"
#       uses: itsmeow/curseforge-upload@v3
#       with:
#         file_path: "build/libs/respawnobelisks-1.1-all.jar"
#         changelog: "https://github.com/RedPxnda/RespawnObelisks/wiki/Changelog"
#         game_endpoint: "minecraft"
#         game_versions: "Minecraft 1.19:1.19.2,Java 17,Forge"
#         project_id: "824852"
#         token: "${{ secrets.CF_API_TOKEN }}"
    - name: Send Discord Embed
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          username: Respawn Obelisk Releases
          color: '#8000ff'
          avatarUrl: https://media.forgecdn.net/avatars/thumbnails/774/979/64/64/638115664626241981_animated.gif
          description: "A new release of Respawn Obelisks has just commenced! Check `https://github.com/RedPxnda/RespawnObelisks/wiki/Changelog` for the changelog."
          details: 'WIP'
          footer: This is a footer.
          text: https://www.curseforge.com/minecraft/mc-mods/respawn-obelisks/
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
